sudo: required
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: ./gradlew setupCIWorkspace
script: ./gradlew build
  
notifications:
  email: false
  webhooks:
    - http://n.tkte.ch/h/4015/Imx73SAk-RAIF3nc9sZb_JWb